#! /bin/bash

web=`pwd`

for file in "serv/common/serverConf.js"; do
    filename=$web/$file
    echo $filename
    # 替换目录
    sed -i "s/home.*diary/home\/lifeix\/temp\/d4\/diary/g"  $filename
done

# 替换域名
sed -i "s/www.iamzc.com/www.zc.com/" $web/serv/common/commonConf.js 
